---
# tasks file for srv1c-role

- name: Install other packages
  include_tasks: install_other_pack.yml

- name: Install RU locale
  include_tasks: install_locale_ru.yml

# Uncomment to remove old packages 1C versions without *.run
- name: Remove old server 1c
  include_tasks: remove_old_srv1c.yml

# Uncomment to remove new packages 1C versions with *.run
- name: Remove new server 1c
  include_tasks: remove_new_srv1c.yml

- name: Install server 1c
  include_tasks: install_srv1c.yml

- name: Install ras
  include_tasks: install_ras.yml

- name: Install ring
  include_tasks: install_ring.yml

# - name: Activating 1C license
#   include_tasks: activate_lic.yml